---

# Relative path to txt file listing genes (more than one file can be listed)
lists:
  - data/Cancer_Genes.txt

# Link to download annotation and the genome file
annotation_url:
  https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/gencode.v43.chr_patch_hapl_scaff.annotation.gff3.gz

fasta_url:
  https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/GRCh38.p13.genome.fa.gz
  
...